### ISSUE TITLE
cannot start service web

### ISSUE THREAD

**Issue by pradeeps** [mattd429/Django-Docker#1]
Hi,

I get this error when running docker-compose up -d

_ERROR: for docker-django-nginx-postgres-redis-containers_web_1  Cannot start service web: b'OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \\"/usr/local/bin/gunicorn\\": stat /usr/local/bin/gunicorn: no such file or directory": unknown'

ERROR: for web  Cannot start service web: b'OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \\"/usr/local/bin/gunicorn\\": stat /usr/local/bin/gunicorn: no such file or directory": unknown'
ERROR: Encountered errors while bringing up the project._

any idea?

**Comment by mabr0wn** [comment]
hey there,

grab the original repo and follow the step-by-step guide [realpython](https://realpython.com/django-development-with-docker-compose-and-machine/), dbader will be able to assist further with any issues.
